A: 0
aa: rand-m9-mstd0.5-inc1
amp: true
apex_amp: false
aq_asym: false
aq_bitw: 6
aq_enable: true
aq_mode: LSQ
aq_neg: null
aq_pos: null
aug_splits: 0
batch_size: 128
bn_eps: null
bn_modules: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 3
clip_grad: null
clip_mode: norm
color_jitter: 0.4
conv_modules: null
cooldown_epochs: 10
crop_pct: 1.0
cutmix: 0.0
cutmix_minmax: null
dataset: cifar10
decay_milestones:
- 20
- 40
decay_rate: 0.1
dist_bn: ''
down_block_type: default
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epoch_repeats: 0.0
epochs: 50
eval_metric: top1
experiment: ''
fl_qmodules:
- conv1
- linear
fl_wq_neg: null
fl_wq_per_channel: false
fl_wq_pos: null
gp: null
hflip: 0.5
img_size: 32
input_size: null
interpolation: bicubic
jsd: false
kd_alpha: 1.0
kd_type: last
local_rank: 0
log_interval: 50
log_wandb: false
lr: 0.001
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.485
- 0.456
- 0.406
min_lr: 1.0e-05
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.0
model: minionn
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_bn: false
no_prefetcher: false
no_resume_opt: false
num_classes: 10
opt: sgd
opt_betas: null
opt_eps: null
output: ''
patience_epochs: 10
pin_mem: false
post_res_bn: false
pretrained: false
qmodules:
- conv2
- conv3
- conv4
- conv5
- conv6
- conv7
quant_firstlast: false
quant_stagewise: false
quant_teacher: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
replace_ln_by_bn: false
reprob: 0.25
resplit: false
resq_asym: false
resq_bitw: 8
resq_enable: true
resq_mode: LSQ
resq_modules: []
resq_neg: null
resq_pos: null
resume: ''
save_images: false
scale:
- 0.8
- 1.0
sched: multistep
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std:
- 0.229
- 0.224
- 0.225
sync_bn: false
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_bn: true
use_distill_head: false
use_dual_skip: false
#use_kd: true
use_layer_scale: false
use_multi_epochs_loader: false
use_relu: true
use_skip: false
use_token_kd: false
val_split: validation
validation_batch_size_multiplier: 1
vflip: 0.0
warmup_epochs: 10
warmup_lr: 1.0e-05
weight_decay: 0.0002
workers: 8
wq_asym: false
wq_bitw: 3
wq_enable: true
wq_mode: LSQ
wq_neg: null
wq_per_channel: false
wq_pos: null
