dataset: torch/cifar100
num_classes: 100
img_size: 32
mean:
    - 0.5071
    - 0.4867
    - 0.4408
std:
    - 0.2675
    - 0.2565
    - 0.2761
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
interpolation: bicubic
train_interpolation: random
# aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0
reprob: 0.25
remode: pixel
amp: True
model: cifar10_reactnet
model_ema: False
batch_size: 128
lr: 75e-5
min_lr: 1e-5
sched: cosine
weight_decay: 1e-5
epochs: 300
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.00001
opt: adamw
smoothing: 0.0
workers: 8
wq_enable: False
wq_mode: "LSQ"
# wq_bitw: 2
wq_pos: 1
wq_neg: -1
aq_enable: False
aq_mode: "LSQ"
# aq_bitw: 2
aq_pos: 1
aq_neg: -1
resq_enable: False
resq_mode: "LSQ"
resq_pos: 1
resq_neg: -1
use_relu: True
post_res_bn: True
qmodules: 
  - "layer.0.conv1"
  - "layer.1.conv1"
  - "layer.1.conv21"
  - "layer.1.conv22"
  - "layer.2.conv1"
  - "layer.2.conv21"
  - "layer.2.conv22"
  - "layer.3.conv1"
  - "layer.3.conv2"
  - "layer.4.conv1"
  - "layer.4.conv21"
  - "layer.4.conv22"
  - "layer.5.conv1"
  - "layer.5.conv2"
  - "layer.6.conv1"
  - "layer.6.conv21"
  - "layer.6.conv22"
  - "layer.7.conv1"
  - "layer.7.conv2"
  - "layer.8.conv1"
  - "layer.8.conv2"
  - "layer.9.conv1"
  - "layer.9.conv2"
  - "layer.10.conv1"
  - "layer.10.conv2"
  - "layer.11.conv1"
  - "layer.11.conv2"
  - "layer.12.conv1"
  - "layer.12.conv21"
  - "layer.12.conv22"
  - "layer.13.conv1"
  - "layer.13.conv2"
resq_modules:
  - "layer.1.relu1"
  - "layer.1.relu2"
  - "layer.2.relu1"
  - "layer.2.relu2"
  - "layer.3.relu1"
  - "layer.3.relu2"
  - "layer.4.relu1"
  - "layer.4.relu2"
  - "layer.5.relu1"
  - "layer.5.relu2"
  - "layer.6.relu1"
  - "layer.6.relu2"
  - "layer.7.relu1"
  - "layer.7.relu2"
  - "layer.8.relu1"
  - "layer.8.relu2"
  - "layer.9.relu1"
  - "layer.9.relu2"
  - "layer.10.relu1"
  - "layer.10.relu2"
  - "layer.11.relu1"
  - "layer.11.relu2"
  - "layer.12.relu1"
  - "layer.12.relu2"
  - "layer.13.relu1"
  - "layer.13.relu2"
