dataset: torch/image_folder
num_classes: 200
val_split: test
img_size: 64
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
interpolation: bicubic
train_interpolation: random
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
batch_size: 128
lr: 0.025
min_lr: 1e-5
sched: cosine
weight_decay: 3e-4
epochs: 300
cooldown_epochs: 10
warmup_epochs: 0
warmup_lr: 0.00001
opt: sgd
momentum: 0.9
smoothing: 0.1
workers: 8
